version: "3"
services:
  webapp:
    container_name: webapp
    image: rubyangxg/jd-qinglong:allinone
    shm_size: 2gb
    ports:
      - "5701:8080"
    environment:
      - SE_NODE_MAX_SESSIONS=4
    volumes:
      - ./env.properties:/env.properties

